version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ${PWD}./app:/

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=ml_app
      - POSTGRES_DB=mldb
      - TZ=Asia/Tokyo
      - PGTZ=Asia/Tokyo
    restart: always
