version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - DBHOST=db
      - DBNAME=mldb
      - DBUSER=ml_app
      - DBPASSWORD=password
      - DBPORT=5432
      - DBCONNECTOR=psycopg2
    ports:
      - 80:80
    command: /wait-for-it.sh
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=ml_app
      - POSTGRES_DB=mldb
      - TZ=Asia/Tokyo
      - PGTZ=Asia/Tokyo
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    stdin_open: true
    restart: always
